# Generated by Django 3.2.14 on 2022-08-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muviapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.CharField(help_text='Año de estreno', max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(help_text='Enlace de la imagen'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(help_text='Sinopsis o resumen de la película', max_length=1000),
        ),
    ]
