# Generated by Django 3.2.14 on 2022-08-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muviapp', '0003_director_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(help_text='Fecha de estreno'),
        ),
    ]
