# Generated by Django 3.2.14 on 2022-08-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muviapp', '0004_alter_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.TimeField(verbose_name='hh:mm:ss'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.CharField(help_text='Año de estreno', max_length=4),
        ),
    ]
