# Generated by Django 3.2.14 on 2022-08-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muviapp', '0005_auto_20220803_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.TimeField(help_text='hh:mm:ss'),
        ),
    ]
