# Generated by Django 3.2.14 on 2022-08-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muviapp', '0006_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='pelicula',
            field=models.ManyToManyField(related_name='f_pelicula', to='muviapp.Pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='f_director', to='muviapp.director'),
        ),
    ]
