# Generated by Django 3.2.14 on 2022-08-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muviapp', '0007_auto_20220804_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.AddField(
            model_name='director',
            name='peliculas',
            field=models.ManyToManyField(to='muviapp.Pelicula'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='directores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muviapp.director'),
        ),
    ]
